apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: z51dyd5fa-nodejs-gitops
  description: This is GitOps manifest for z51dyd5fa-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=z51dyd5fa-nodejs
    backstage.io/kubernetes-id: z51dyd5fa-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: z51dyd5fa-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:z51dyd5fa-nodejs
