apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z51dyd5fa-nodejs
  janus-idp.io/tekton: z51dyd5fa-nodejs
  backstage.io/kubernetes-id: z51dyd5fa-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z51dyd5fa-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
